services:
  _defaults:
    autowire: true
    autoconfigure: true

  Hyoa\TwigProfilerVariablesBundle\Controller\:
    resource: '../../Controller'
    tags: ['controller.service_arguments']

  templating.engine.profiler_variables:
    class: Hyoa\TwigProfilerVariablesBundle\Engine\TwigEngineDecorator
    arguments:
      - "@twig"
      - "@templating.name_parser"
      - "@twig.profiler.data_collector"
    tags:
      - { name: "templating.engine" }

  twig.profiler.data_collector:
    class: Hyoa\TwigProfilerVariablesBundle\DataCollector\VariablesCollector
    tags:
      - { name: data_collector, template: '@TwigProfilerVariables/Collector/variables', id: 'twig_profiler_variables.collector' }
